export const surpriseMePrompts = [
  'A giant octopus playing the drums in a rock band, digital art', 'An oil painting of a mermaid riding a unicorn through a field of poppies', 'A group of penguins having a picnic on the moon, digital art', 'A 3D render of a city made entirely out of sweets and candy, with gumdrop trees and lollipop lampposts', 'A portrait of a lion wearing a top hat and monocle, surrounded by books', 'A photo of a red panda sitting on a rainbow, with a lightning storm in the background', 'A watercolor painting of a hummingbird sipping nectar from a flower garden', 'A neon sign that reads "Coffee and Dreams" against a night sky background, photography', 'A surrealistic painting of a giraffe in a suit riding a bicycle, with a cityscape in the background', 'A digital art piece of a dragon flying over a mountain range, breathing fire', 'A photograph of a jellyfish glowing in the dark ocean depths', 'A painting of a peacock displaying its feathers in front of a full moon', 'A 3D render of a futuristic city with flying cars and holographic advertisements', 'A photo of a husky puppy sleeping on a pile of autumn leaves', 'An oil painting of a flamingo wearing a tutu, standing on one leg', 'A black and white photo of a person jumping off a diving board into a pool with crystal clear water', 'A digital art piece of a robot bartender mixing drinks in a post-apocalyptic world', 'A watercolor painting of a field of lavender at sunset', 'A photograph of a baby elephant playing in a mud puddle', 'A colorful abstract painting with geometric shapes and patterns', 'A photo of a corgi wearing a party hat and eating a slice of birthday cake', 'A 3D render of a futuristic train station with sleek design and neon lighting', 'A painting of a sunflower field with a rainbow in the background', 'A digital art piece of an alien planet with strange creatures and plants', 'A photo of a koala sleeping in a tree, with a city skyline in the background', 'An oil painting of a phoenix rising from the ashes', 'A watercolor painting of a dragonfly perched on a lily pad', 'A black and white photo of a person walking down a deserted road into a foggy distance', 'A 3D render of a spaceship hovering over an alien planet with two suns', 'A photograph of a butterfly landing on a flower', 'A painting of a wolf howling at the moon', 'A digital art piece of a futuristic underwater city with bioluminescent sea creatures', 'A photo of a baby giraffe nuzzling its mothers neck', 'A surrealistic painting of a flamingo riding a bicycle through a desert landscape', 'A watercolor painting of a hummingbird with vibrant colors and intricate details', 'A 3D render of a magical forest with glowing mushrooms and fireflies', 'A photo of a red fox sitting on a log in a snowy forest', 'An oil painting of a peacock feather with striking colors and intricate patterns', 'A digital art piece of a space traveler exploring a galaxy filled with colorful nebulas', 'A painting of a sunset over a calm ocean, with birds flying in the distance', 'A photograph of a tiger swimming in a river, with lush greenery in the background', 'A 3D render of a futuristic laboratory with glowing test tubes and complex machinery', 'A black and white photo of a person standing on top of a mountain, looking out at the horizon', 'A watercolor painting of a cherry blossom tree in full bloom', 'A surrealistic painting of a whale flying through the clouds, with a rainbow in the background', 'A photo of a baby seal playing in the ocean waves', 'A digital art piece of a city skyline at night, with colorful lights and reflections in the water', 'An oil painting of a peacock with its feathers fully displayed in front of a waterfall', 'A 3D render of a futuristic space station orbiting around a planet with a ring'
,
 'A portrait of a woman wearing a traditional Indian saree, holding a basket of flowers',
'A digital art piece of a man surfing on a giant wave, with the sun setting in the background',
 'A photo of a group of friends hiking up a mountain, with backpacks and hiking poles',
 'An oil painting of a ballerina performing on stage, surrounded by flowers',
 'A 3D render of a futuristic city with people riding hoverboards and wearing sleek silver suits',
 'A black and white photo of a person playing guitar on a street corner, with a crowd gathered around',
 'A watercolor painting of a couple dancing under a starry sky, with fairy lights hanging overhead',
 'A surrealistic painting of a woman floating in a bubble, wearing a flowing dress and holding an umbrella',
 'A photo of a man bungee jumping off a bridge, with a river below and mountains in the distance',
 'A painting of a woman meditating on a mountaintop, with a sunrise in the background',
 'A digital art piece of a person practicing martial arts in front of a temple, with cherry blossom trees in bloom',
 'A photograph of a young girl playing hopscotch on a city sidewalk, with skyscrapers in the background',
 'An oil painting of a cowboy riding a horse through a desert landscape, with a storm brewing in the distance',
 'A 3D render of a futuristic skate park with neon lighting and ramps of all shapes and sizes',
 'A watercolor painting of a woman picking fruit from a tree in a lush garden',
 'A photo of a man skydiving above a cloud-filled sky, with a parachute trailing behind him',
 'A painting of a man fishing on a peaceful lake, with a forest backdrop',
 'A digital art piece of a woman practicing yoga on a beach, with waves crashing in the background',
 'A black and white photo of a person breakdancing on a city street, with graffiti-covered walls',
 'A surrealistic painting of a person sitting in a giant teacup, surrounded by flowers and vines',
 'A photo of a woman rock climbing up a steep cliff face, with ropes and safety gear attached',
 'An oil painting of a woman walking through a snowy forest, wearing a red coat and carrying a basket of berries',
 'A 3D render of a futuristic sports stadium, with holographic displays and flying vehicles',
 'A watercolor painting of a man sipping tea in a traditional Japanese garden, with koi fish swimming in a pond',
 'A photograph of a couple ice skating on a frozen lake, with snow-covered trees in the background',
 'A painting of a woman riding a bicycle through a field of sunflowers, with a blue sky overhead',
 'A digital art piece of a person practicing archery in a forest clearing, with mist rising from the ground',
 'A photo of a group of friends playing beach volleyball on a sunny day, with palm trees swaying in the breeze',
 'A black and white photo of a person skateboarding through an empty city street, with a full moon in the background',
 'A surrealistic painting of a woman standing in front of a giant clock, with gears and mechanisms visible behind her',
];

